#!/usr/bin/env python3

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

import argparse
import csv
import re

from transliterate import translit

from objectreport import ObjectReport


def parse_time(time_str):
    if not re.match(r"[0-9]{1,2}\.[0-9]{2}", time_str):
        return None

    return time_str.replace('.', ':')


def parse_schedule_csv(csv_file):
    csv_reader = csv.DictReader(csv_file)

    schedule = []
    for row in csv_reader:
        if 'по предварительной заявке' in row['Наименование моста']:
            continue

        first_interval = (parse_time(row['Время первой разводки']), parse_time(row['Время первой сводки']))
        second_interval = (parse_time(row['Время второй разводки']), parse_time(row['Время второй сводки']))
        intervals = [first_interval] if second_interval[0] is None else [first_interval, second_interval]

        coordinates = row['Координаты'].split(',')

        schedule.append({
            'bridge_name': row['Наименование моста'],
            'intervals': intervals,
            'coordinates': {
                'latitude': float(coordinates[0]),
                'longitude': float(coordinates[1]),
            }
        })

    return schedule


def create_bridge_beacons(bridges, callsign):
    beacons = []
    for bridge in bridges:
        object_name = translit(re.sub('мост', '', bridge['bridge_name'], flags=re.I), 'ru', reversed=True)
        comment = 'Open ' + ' and '.join([f'from {frm} to {to}' for (frm, to) in bridge['intervals']])

        beacon = ObjectReport({
            'fromcall': callsign,
            'tocall': 'APRS',
            'symbol_table': '\\',
            'symbol': 'N',
            'object_name': object_name,
            'latitude': bridge['coordinates']['latitude'],
            'longitude': bridge['coordinates']['longitude'],
            'comment': comment,
        })
        beacons.append(beacon)

    return beacons


if __name__ == '__main__':
    args_parser = argparse.ArgumentParser(description='Videos to images')
    args_parser.add_argument(
        '--schedule-csv',
        type=argparse.FileType('r', encoding='utf-8-sig'),
        help='Drawbridges opening times CSV from https://data.gov.spb.ru/irsi/7830001853-grafik-razvodki-mostov/',
        required=True,
    )
    args_parser.add_argument(
        '--callsign',
        type=str,
        help='Callsign',
        required=True,
    )
    args = args_parser.parse_args()

    schedule = parse_schedule_csv(args.schedule_csv)
    bridge_beacons = create_bridge_beacons(schedule, args.callsign)
    print(bridge_beacons)
